config/routes.rb
Rails.application.routes.draw do
  resources :changes

  resources :stories

  resources :actions

  resources :users

  resources :states

end

app/models/change.rb
class Change < ActiveRecord::Base
  belongs_to :story
  belongs_to :user
  belongs_to :state_from, :class_name => "State"
  belongs_to :state_to, :class_name => "State"

  validates :story, presence: true
  validates :user, presence: true
  validates :state_from, presence: true
  validates :state_to, presence: true

  def execution_time
    Change.all.each do |change|
    end
  end
end

app/controllers/changes_controller.rb
class ChangesController < ApplicationController
  before_action :set_change, only: [:show, :edit, :update, :destroy]

  # GET /changes
  # GET /changes.json
  def index
    @changes = Change.order("story_id desc").all

    sfrom = Hash.new
    sto = Hash.new

    @sdiff = Hash.new

    Change.order("story_id, date").all.each do |change|
      timedate = ActiveSupport::TimeZone["Brasilia"].parse(change.date.to_s).to_i

      sfrom[change.story.id.to_s + "-" + change.state_from.order.to_s] = timedate

      if sto[change.story.id.to_s + "-" + change.state_to.order.to_s].nil?
        sto[change.story.id.to_s + "-" + change.state_to.order.to_s] = timedate
      else
        sto[change.story.id.to_s + "-" + change.state_to.order.to_s] = sto[change.story.id.to_s + "-" + change.state_to.order.to_s] + timedate
      end

      puts sto.inspect
      unless sto[change.story.id.to_s + "-" + change.state_from.order.to_s].nil?
        puts timedate - sto[change.story.id.to_s + "-" + change.state_from.order.to_s]
        puts TimeDifference.between(timedate, sto[change.story.id.to_s + "-" + change.state_from.order.to_s]).in_hours
        if @sdiff[change.state_from.title].nil? 
          @sdiff[change.state_from.title] = TimeDifference.between(timedate, sto[change.story.id.to_s + "-" + change.state_from.order.to_s]).in_hours
        else
          @sdiff[change.state_from.title] = @sdiff[change.state_from.title] + TimeDifference.between(timedate, sto[change.story.id.to_s + "-" + change.state_from.order.to_s]).in_hours
        end
      end
    end

  end

  # GET /changes/1
  # GET /changes/1.json
  def show
  end

  # GET /changes/new
  def new
    @change = Change.new
  end

  # GET /changes/1/edit
  def edit
  end

  # POST /changes
  # POST /changes.json
  def create
    @change = Change.new(change_params)

    respond_to do |format|
      if @change.save
        format.html { redirect_to @change, notice: 'Change was successfully created.' }
        format.json { render :show, status: :created, location: @change }
      else
        format.html { render :new }
        format.json { render json: @change.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /changes/1
  # PATCH/PUT /changes/1.json
  def update
    respond_to do |format|
      if @change.update(change_params)
        format.html { redirect_to @change, notice: 'Change was successfully updated.' }
        format.json { render :show, status: :ok, location: @change }
      else
        format.html { render :edit }
        format.json { render json: @change.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /changes/1
  # DELETE /changes/1.json
  def destroy
    @change.destroy
    respond_to do |format|
      format.html { redirect_to changes_url, notice: 'Change was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_change
      @change = Change.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def change_params
      params.require(:change).permit(:story_id, :user_id, :state_from_id, :state_to_id, :date)
    end
end

app/helpers/changes_helper.rb
module ChangesHelper
end

app/views/changes/_form.html.erb
<%= form_for(@change) do |f| %>
  <% if @change.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@change.errors.count, "error") %> prohibited this change from being saved:</h2>

      <ul>
      <% @change.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :story_id %><br>
   <%= f.collection_select(:story_id,
                            Story.all,
                            :id,
                            :title,
                            { :prompt => true })
    %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
   <%= f.collection_select(:user_id,
                            User.all,
                            :id,
                            :name,
                            { :prompt => true })
    %>
  </div>
  <div class="field">
    <%= f.label :state_from %><br>
  <%= f.collection_select(:state_from_id,
                            State.all,
                            :id,
                            :title,
                            { :prompt => true })
    %>
</div>
  </div>
  <div class="field">
    <%= f.label :state_to %><br>
   <%= f.collection_select(:state_to_id,
                            State.all,
                            :id,
                            :title,
                            { :prompt => true })
    %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date, :order => [:day,:month,:year] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/changes/edit.html.erb
<h1>Editing change</h1>

<%= render 'form' %>

<%= link_to 'Show', @change %> |
<%= link_to 'Back', changes_path %>

app/views/changes/index.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<h1>Listing changes</h1>

<table width="100%">
  <thead>
    <tr>
      <th>Story</th>
      <th>User</th>
      <th>Initial State</th>
      <th>Final State</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @changes.each do |change| %>
      <tr align="center">
        <td><%= change.story.title %></td>
        <td><%= change.user.name %></td>
        <td><%= change.state_from.title %></td>
        <td><%= change.state_to.title %></td>
        <td><%= change.date.strftime("%d/%m/%Y %H:%M:%S") %></td>
        <td><%= link_to 'Show', change %></td>
        <td><%= link_to 'Edit', edit_change_path(change) %></td>
        <td><%= link_to 'Destroy', change, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% @sdiff.each do |diff| %>
<%= diff %>
<% end %>
<br>
<%= pie_chart Change.group(:state_to).count %>

<%= bar_chart @sdiff %>
<%= link_to 'New Change', new_change_path %>

app/views/changes/new.html.erb
<h1>New change</h1>

<%= render 'form' %>

<%= link_to 'Back', changes_path %>

app/views/changes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Story:</strong>
  <%= @change.story.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @change.user.name %>
</p>

<p>
  <strong>State from:</strong>
  <%= @change.state_from.title %>
</p>

<p>
  <strong>State to:</strong>
  <%= @change.state_to.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @change.date.strftime("%d/%m/%Y %H:%M:%S") %>
</p>

<%= link_to 'Edit', edit_change_path(@change) %> |
<%= link_to 'Back', changes_path %>